apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap-server
          image: "docker.io/osixia/openldap:latest"
