apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: auth
spec:
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
    - name: ldaps
      port: 636
      targetPort: 636
