---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ldap-anyuid
  namespace: auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ldap-anyuid
  namespace: auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: ldap-anyuid
  namespace: auth
