apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-idp.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
