apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: granite-vision-model
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
