apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - https://github.com/kubernetes-csi/csi-driver-smb/raw/refs/heads/master/deploy/v1.20.3/rbac-csi-smb.yaml
  - https://github.com/kubernetes-csi/csi-driver-smb/raw/refs/heads/master/deploy/v1.20.3/csi-smb-driver.yaml
  - https://github.com/kubernetes-csi/csi-driver-smb/raw/refs/heads/master/deploy/v1.20.3/csi-smb-controller.yaml
  - https://github.com/kubernetes-csi/csi-driver-smb/raw/refs/heads/master/deploy/v1.20.3/csi-smb-node.yaml
