apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Cluster Observability Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-cluster-observability-operator
