---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  annotations:
    observability.openshift.io/log-level: debug
  name: log-audit
  namespace: openshift-logging
spec:
  managementState: Managed
  outputs:
    - name: http
      otlp:
        url: 'http://http-receiver.diag.svc.cluster.local:8080'
      type: otlp
      tuning:
        compression: gzip
        deliveryMode: AtLeastOnce
        maxRetryDuration: 20
        maxWrite: 10M
        minRetryDuration: 5
  pipelines:
    - inputRefs:
        # - application
        # - infrastructure
        - audit
      name: logs-to-http
      outputRefs:
        - http
  serviceAccount:
    name: logging-collector
