---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  annotations:
    observability.openshift.io/log-level: debug
  name: log-infra
  namespace: openshift-logging
spec:
  managementState: Managed
  outputs:
    - name: http
      otlp:
        url: 'http://http-receiver.diag.svc.cluster.local:8080'
      type: otlp
      tuning:
        compression: gzip
        deliveryMode: AtLeastOnce
        maxRetryDuration: 20
        maxWrite: 10M
        minRetryDuration: 5
    - name: raw
      syslog:
        url: tcp://socat.diag.svc.cluster.local:6666
        rfc: RFC5424
      type: syslog
  pipelines:
    - inputRefs:
        # - application
        - infrastructure
        # - audit
      name: logs-to-http
      outputRefs:
        - http
        - raw
  serviceAccount:
    name: logging-collector
