# syntax=docker/dockerfile:1.3-labs
ARG IMAGE_NAME=registry.access.redhat.com/ubi9/ubi
FROM ${IMAGE_NAME}

# hadolint ignore=DL3002
USER 0

# install: common tools
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf install -y bash curl-minimal diffutils git nano openssh-clients rsync vim wget zip && \
    /usr/bin/crb enable && \
    dnf clean all && \
    rm -rf /var/cache/yum/*

# todo: install cli tools during env init / not in container
ARG OC4_URL="https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz"
ARG OC_MIRROR_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/oc-mirror.tar.gz"

RUN curl -sL "${OC4_URL}" | \
      tar -C /usr/local/bin -vzxf- oc kubectl && \
      /usr/local/bin/oc completion bash > /etc/bash_completion.d/oc && \
      echo "source /etc/bash_completion.d/oc" >> /etc/skel/.bashrc && \
    curl -sL "${OC_MIRROR_URL}" | \
      tar -C /usr/local/bin -vzxf- --no-same-owner oc-mirror && \
      chmod +x /usr/local/bin/oc-mirror && \
      /usr/local/bin/oc-mirror completion bash > /etc/bash_completion.d/oc-mirror && \
      echo "source /etc/bash_completion.d/oc-mirror" >> /etc/skel/.bashrc

# setup: user
# hadolint ignore=SC2028
RUN \
    sed -i '/^export PS1=.*/d' /etc/skel/.bashrc && \
    echo "export PS1='\W \`git branch --show-current 2>/dev/null | sed -r -e \"s@^(.+)@\(\1\) @\"\`$ '" >> /etc/skel/.bashrc && \
    # cp /etc/gitconfig /etc/skel/.gitconfig && \
    useradd -u 1001 \
      -G wheel,root \
      -d /home/user \
      --shell /bin/bash \
      -m user && \
    chgrp -R 0 /home && \
    chmod -R g=u /etc/passwd /etc/group /home

# labels for container catalog
LABEL summary="devfile base developer image"
LABEL description="image with base developers tools"
LABEL io.k8s.display-name="devfile-developer-base"
LABEL io.openshift.expose-services=""

# USER 1001
ENV HOME=/home/user
VOLUME /home/user
WORKDIR /home/user
