FROM quay.io/modh/cuda-notebooks:cuda-jupyter-tensorflow-ubi9-python-3.9-2023a-weekly

USER 0

# install graphviz - the hard way
RUN dnf install -y gcc g++ diffutils && \
    wget https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/8.0.5/graphviz-8.0.5.tar.gz && \
    tar zxf graphviz-8.0.5.tar.gz && \
    cd graphviz-8.0.5 && \
    ./configure && \
    make && \
    make install && \
    yum history undo last -y && \
    yum clean all && \
    cd .. && \
    rm -rf graphviz-*

# upgrade all the things; add libGL
RUN dnf upgrade -y && \
    dnf install -y mesa-libGL && \
    dnf -y clean all

USER 1001

# install the pip things
RUN pip install \
    elyra==3.* \
    opencv-python==4.7.* \
    opencv-contrib-python==4.7.* \
    matplotlib==3.6.* \
    protobuf==3.19.* \
    imutils==0.5.* \
    tensorflow_datasets==4.9.*
