---
kind: Service
apiVersion: v1
metadata:
  name: samba
  labels:
    app: samba
spec:
  type: ClusterIP  # use "LoadBalancer" to get a public ip
  selector:
    app: samba
  ports:
    - port: 445
      name: samba
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      name: samba
      labels:
        app: samba
    spec:
      serviceAccountName: samba-server
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: samba
          image: quay.io/samba.org/samba-server:latest
          # command:
          # - /bin/sh
          # - -c
          # - |
          #   #/bin/sh
          #   smbd --version
          #   samba-container --help

          #   sleep infinity
          volumeMounts:
            - mountPath: /share
              name: empty
          #   - mountPath: /run/samba
          #     name: empty
          #     subPath: run
          #   - mountPath: /var/lib/samba/
          #     name: empty
          #     subPath: var
          ports:
            - containerPort: 445
      volumes:
        - name: empty
          emptyDir: {}
