apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sandbox

resources:
  - ../../../components/cluster-configs/namespaces/instance/sandbox
  - ../../../components/app-configs/httpbin/base

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value: {}
  target:
    kind: Deployment
    name: httpbin
