apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sandbox

resources:
  - ../../../components/cluster-configs/namespaces/instance/sandbox
  - ../../../components/app-configs/httpbin/base

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value: {}
  target:
    kind: Deployment
    name: httpbin
- patch: |-
    - op: replace
      path: /spec/hard
      value:
        requests.cpu: '1'
        requests.memory: 1Gi
        limits.cpu: '32'
        limits.memory: 128Gi
        requests.nvidia.com/gpu: '0'
        requests.amd.com/gpu: '0'
  target:
    kind: ResourceQuota
    name: quota-compute
