---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ibm-granite
  namespace: modelcars
spec:
  tags:
  - name: latest
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: granite-vision-3.3-2b
  namespace: modelcars
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'ibm-granite:granite-vision-3.3-2b'
  strategy:
    type: Docker
    dockerStrategy:
      # from:
      #   kind: DockerImage
      #   name: 'quay.io/fedora/fedora-minimal:43'
  source:
    type: Dockerfile
    dockerfile: |
      # Base image for the modelcar Granite image
      FROM quay.io/redhat-ai-services/huggingface-downloader:latest as base

      # The model repo to download
      ENV MODEL_REPO="ibm-granite/granite-vision-3.3-2b"

      # Download the necessary model files
      RUN python3 download_model.py --model-repo ${MODEL_REPO}

      # Final image containing only the essential model files
      FROM registry.access.redhat.com/ubi9/ubi-micro:9.6

      # Copy only the necessary model files from the base image
      COPY --from=base /models /models

      # Set the user to 1001
      USER 1001
  runPolicy: SerialLatestOnly
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
