FROM registry.access.redhat.com/ubi9/ubi:latest

RUN dnf upgrade -y && \
    dnf install -y openssh-clients && \    
    dnf clean all && \
    ssh -V

USER 1001

COPY reverse_tunnel.sh reverse_tunnel.env.sample /app

WORKDIR /app
VOLUME /config

ENV ENV_FILE=/config/reverse_tunnel.env \
    SSH_KEY=/config/id_ed25519

ENTRYPOINT /app/reverse_tunnel.sh
