---
kind: Service
apiVersion: v1
metadata:
  name: samba
  labels:
    app: samba
spec:
  type: ClusterIP  # use "LoadBalancer" to get a public ip
  selector:
    app: samba
  ports:
    - port: 445
      name: samba
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      name: samba
      labels:
        app: samba
    spec:
      serviceAccountName: samba-server
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: samba
          image: quay.io/samba.org/samba-server:latest
          env:
            - name: SAMBACC_CONFIG
              value: /etc/samba/container.json:/config/container.yaml
          ports:
            - containerPort: 445
          volumeMounts:
            - mountPath: /share
              name: empty
            - mountPath: /config
              name: config
      volumes:
        - name: empty
          emptyDir: {}
        - name: config
          configMap:
            name: smb-config
