apiVersion: v1
data:
  container.yaml: |
    samba-container-config: v0
    # Define top-level configurations
    configs:
      demo:
        globals: ["default"]
        shares:
          - share
    # Define Global Options
    globals:
      default:
        options:
          load printers: "no"
          printing: "bsd"
          printcap name: "/dev/null"
          disable spoolss: "yes"
          guest ok: "no"
          security: "user"
          server min protocol: "SMB2"
    # Define Shares
    shares:
      share:
        options:
          path: /share
          read only: "no"
    # Define users
    users:
      all_entries:
        - {"name": "sambauser", "password": "samba"}
        - {"name": "otheruser", "password": "insecure321"}
kind: ConfigMap
metadata:
  name: smb-config
