apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- link-github.yaml

# - ../../components/app-configs/rhoai-config
# - ../../demos/overlays/rhoai-workshop-ready

# - ../../components/cluster-configs/rbac/overlays/workshop
# - ../../components/cluster-configs/login/overlays/htpasswd

# patches:
#   - path: dashboard-config-cr.yaml
#   - target:
#       kind: ConsoleNotification
#       name: banner-demo
#     patch: |-
#       - op: replace
#         path: /spec/text
#         value: 'WORKSHOP: Fraud Detection w/ Red Hat OpenShift AI'
