apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
spec:
  template:
    spec:
      containers:
        - name: server
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/sh

              genpass(){
                < /dev/urandom LC_ALL=C tr -dc Aa-zZ0-9 | head -c "${1:-32}"
              }

              USER=${USER:-admin}
              PASSWORD=${PASSWORD:-$(genpass 16)}

              echo "
                USER:     ${USER}
                PASSWORD: ${PASSWORD}
              "
              
              rclone serve webdav \
                --addr :8080 \
                --user ${USER} \
                --pass ${PASSWORD} \
                /data

              sleep infinity
