apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-map.yaml
  - cluster-role-bindings.yaml
  - cluster-role.yaml
  - namespace.yaml
  - scc.yaml
  - service-account.yaml
