apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: hp-2m
  name: 50-kargs-hugepages-1g
spec:
  kernelArguments:
  - hugepagesz=1G 
  - hugepages=2