apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-receiver
    app.kubernetes.io/component: http-receiver
    app.kubernetes.io/instance: http-receiver
    app.kubernetes.io/name: http-receiver
    app.kubernetes.io/part-of: http-receiver
  name: http-receiver
spec:
  ports:
  - name: 8080-tcp
    port: 8080
  selector:
    deploy: http-receiver
