FROM quay.io/modh/odh-generic-data-science-notebook:v2-2023a-20230322

COPY Pipfile.lock /opt/app-root/bin/

RUN cd /opt/app-root/bin \
 && micropipenv install \
 && rm -f Pipfile.lock \
 && chmod -R g+w /opt/app-root/lib/python3.9/site-packages \
 && fix-permissions /opt/app-root -P
